server:
  port: 8080
logging:
  level:
    root: WARN
    com:
      travel:
        portal: TRACE

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/travelportal?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
    password: admin
    username: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  profiles:
    active: dev

  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddl-auto: update
